
package io.vpplab.kpx.loadforecast.prod;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LoadForecastPort", targetNamespace = "http://www.kpx.or.kr/2014/service/loadforecast")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoadForecastPort {


    /**
     * 
     * @param request
     * @return
     *     returns io.vpplab.kpx.loadforecast.prod.GetLoadForecastResponseMessageType
     * @throws LoadForecastFaultMessage
     */
    @WebMethod(operationName = "GetLoadForecast", action = "http://www.kpx.or.kr/2014/service/loadforecast")
    @WebResult(name = "GetResponseLoadForecasts", targetNamespace = "http://www.kpx.or.kr/2014/schema/loadforecast#", partName = "response")
    public GetLoadForecastResponseMessageType getLoadForecast(
        @WebParam(name = "GetRequestLoadForecasts", targetNamespace = "http://www.kpx.or.kr/2014/schema/loadforecast#", partName = "request")
        GetLoadForecastRequestMessageType request)
        throws LoadForecastFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns io.vpplab.kpx.loadforecast.prod.GetRTLoadForecastResponseMessageType
     * @throws LoadForecastFaultMessage
     */
    @WebMethod(operationName = "GetRTLoadForecast", action = "http://www.kpx.or.kr/2014/service/rtloadforecast")
    @WebResult(name = "GetResponseRTLoadForecasts", targetNamespace = "http://www.kpx.or.kr/2014/schema/loadforecast#", partName = "response")
    public GetRTLoadForecastResponseMessageType getRTLoadForecast(
        @WebParam(name = "GetRequestRTLoadForecasts", targetNamespace = "http://www.kpx.or.kr/2014/schema/loadforecast#", partName = "request")
        GetRTLoadForecastRequestMessageType request)
        throws LoadForecastFaultMessage
    ;

}
