
package io.vpplab.kpx.loadforecast.prod;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "FaultMessage", targetNamespace = "http://iec.ch/TC57/2011/schema/message")
public class LoadForecastFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultMessageType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LoadForecastFaultMessage(String message, FaultMessageType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public LoadForecastFaultMessage(String message, FaultMessageType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: io.vpplab.kpx.loadforecast.prod.FaultMessageType
     */
    public FaultMessageType getFaultInfo() {
        return faultInfo;
    }

}
