
package io.vpplab.kpx.loadforecast.prod;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LoadForecastService", targetNamespace = "http://www.kpx.or.kr/2014/service/loadforecast", wsdlLocation = "https://www.kmos.kr/wsdl/test/LoadForecast.wsdl")
public class LoadForecastService
    extends Service
{

    private static final URL LOADFORECASTSERVICE_WSDL_LOCATION;
    private static final WebServiceException LOADFORECASTSERVICE_EXCEPTION;
    private static final QName LOADFORECASTSERVICE_QNAME = new QName("http://www.kpx.or.kr/2014/service/loadforecast", "LoadForecastService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.kmos.kr/wsdl/test/LoadForecast.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOADFORECASTSERVICE_WSDL_LOCATION = url;
        LOADFORECASTSERVICE_EXCEPTION = e;
    }

    public LoadForecastService() {
        super(__getWsdlLocation(), LOADFORECASTSERVICE_QNAME);
    }

    public LoadForecastService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOADFORECASTSERVICE_QNAME, features);
    }

    public LoadForecastService(URL wsdlLocation) {
        super(wsdlLocation, LOADFORECASTSERVICE_QNAME);
    }

    public LoadForecastService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOADFORECASTSERVICE_QNAME, features);
    }

    public LoadForecastService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoadForecastService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoadForecastPort
     */
    @WebEndpoint(name = "LoadForecastPort")
    public LoadForecastPort getLoadForecastPort() {
        return super.getPort(new QName("http://www.kpx.or.kr/2014/service/loadforecast", "LoadForecastPort"), LoadForecastPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoadForecastPort
     */
    @WebEndpoint(name = "LoadForecastPort")
    public LoadForecastPort getLoadForecastPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.kpx.or.kr/2014/service/loadforecast", "LoadForecastPort"), LoadForecastPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOADFORECASTSERVICE_EXCEPTION!= null) {
            throw LOADFORECASTSERVICE_EXCEPTION;
        }
        return LOADFORECASTSERVICE_WSDL_LOCATION;
    }

}
